FROM node
COPY . .
RUN npm install
EXPOSE 8000
# ENV variables for following exercises
# ENV FRONT_URL=
# Redis
# ENV REDIS=
# Postgres db creds
# DB_USERNAME=<database user username>
# DB_PASSWORD=<database user password>
# DB_NAME=<database-name> defaults to DB_USERNAME if not set.
# DB_HOST=<hostname> defaults to "localhost" if not set.

CMD npm start
