version: "3.7"
services:
        frontend:
                build: ./frontend
                ports: 
                        - 5000:5000
        backend:
                build: ./backend
                ports:
                        - 8000:8000
                volumes:
                        - F:\Documents\Opiskelu\DevOpsDocker2019\backend\logs.txt:/logs.txt
                environment:
                        - REDIS=redis
                networks:
                        - backend-network
         
        redis:
                image: "redis:alpine"
                volumes:
                        - ./redis/data:/data
                networks:
                        - backend-network

networks:
        backend-network:
